name: Nomad Consul Pi Raw Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - uses: actions/checkout@v4
    - name: Pull the config.toml
      run: curl https://raw.githubusercontent.com/L3tum/NomadConsulPi/refs/heads/master/config.toml --output ./config.toml
    - name: Replace values in config.toml with secrets
      run: |
        sed -i -e "s%TAILSCALE_SECRET%${{ secrets.TS_AUTHOR_KEY }}%g" ./config.toml
        sed -i -e "s%CONSUL_GOSSIP_KEY%${{ secrets.CONSUL_GOSSIP_KEY }}%g" ./config.toml
    - name: Build RAW
      id: build-raw
      uses: osbuild/bootc-image-builder-action@v0.0.2
      with:
        config-file: ./config.toml
        image: docker.io/l3tum/nomad-consul-pi:latest
        types: |
          raw
        rootfs: xfs
    - name: Checkout artifact repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ARTIFACTREPOTOKEN }}
        repository: l3tum/artifact-repo
        ref: master
        path: artifactrepo
    - name: Move Artifact to artifact repo
      run: |
        mkdir -p artifactrepo/nomad-consul-pi
        cp ${{ steps.build-raw.outputs.output-directory }}/* artifactrepo/nomad-consul-pi/
    - name: Commit files
      run: |
        cd artifactrepo
        git config --local user.email "BootC@test.com"
        git config --local user.name "BootC"
        git commit -a -m "Upload new nomad-consul-pi"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ARTIFACTREPOTOKEN }}
        repository: l3tum/artifact-repo
        force: true
        directory: artifactrepo
    - name: Delete config.toml
      if: always()
      run: rm -rf ./config.toml
